In [1]:
# IMPORT LIBRERIA E PERCORSO FILE GREZZI

import pandas as pd

PATH_RAW = r"C:\Users\bello\Desktop\CAPSTONE\Capstone_calcio_2425\data_raw (dati_originali)"

In [2]:
# CARICAMENTO FILE GREZZI

serie_a_raw = pd.read_csv(PATH_RAW + r"\matches_serie_a.csv")
premier_raw = pd.read_csv(PATH_RAW + r"\matches_premier_league.csv")
liga_raw = pd.read_csv(PATH_RAW + r"\matches_liga.csv")

In [3]:
# ANTEPRIMA DATI GREZZI

print("SERIE A GREZZO")
display(serie_a_raw.head())

print("PREMIER GREZZO")
display(premier_raw.head())

print("LIGA GREZZO")
display(liga_raw.head())

SERIE A GREZZO

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,I1,17/08/2024,17:30,Genoa,Inter,2,2,D,1,1,...,2.06,1.87,2.08,1.85,2.13,1.89,2.05,1.82,2.09,1.90
1,I1,17/08/2024,17:30,Parma,Fiorentina,1,1,D,1,0,...,2.07,1.86,2.05,1.88,2.07,1.91,2.01,1.84,2.09,1.90
2,I1,17/08/2024,19:45,Empoli,Monza,0,0,D,0,0,...,2.10,1.83,2.12,1.83,2.14,1.86,2.08,1.79,2.16,1.85
3,I1,17/08/2024,19:45,Milan,Torino,2,2,D,0,1,...,1.89,2.04,1.88,2.04,1.92,2.10,1.84,2.02,1.90,2.08
4,I1,18/08/2024,17:30,Bologna,Udinese,1,1,D,0,0,...,2.10,1.83,2.09,1.85,2.15,1.86,2.08,1.81,2.12,1.87

PREMIER GREZZO

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

LIGA GREZZO

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,SP1,15/08/2024,18:00,Ath Bilbao,Getafe,1,1,D,1,0,...,2.08,1.73,2.17,1.76,2.19,1.82,2.12,1.77,2.19,1.82
1,SP1,15/08/2024,20:30,Betis,Girona,1,1,D,1,0,...,2.01,1.89,2.03,1.89,2.10,1.94,2.01,1.85,2.08,1.90
2,SP1,16/08/2024,18:00,Celta,Alaves,2,1,H,0,1,...,1.82,2.11,1.83,2.10,1.84,2.12,1.79,2.08,1.85,2.14
3,SP1,16/08/2024,20:30,Las Palmas,Sevilla,2,2,D,1,1,...,1.86,2.07,1.87,2.07,1.89,2.11,1.86,2.03,1.90,2.09
4,SP1,17/08/2024,18:00,Osasuna,Leganes,1,1,D,0,1,...,1.88,2.05,1.88,2.04,1.91,2.06,1.87,2.00,1.94,2.05

In [4]:
# SELEZIONE STESSE 10 COLONNE

COLONNE = ["Date","HomeTeam","AwayTeam","FTHG","FTAG","FTR","HS","AS","HST","AST"]

serie_a_clean = serie_a_raw[COLONNE]
premier_clean = premier_raw[COLONNE]
liga_clean = liga_raw[COLONNE]

In [5]:
# ANTEPRIMA DATI FORMATTATI

print("SERIE A CLEAN")
display(serie_a_clean.head())

print("PREMIER CLEAN")
display(premier_clean.head())

print("LIGA CLEAN")
display(liga_clean.head())

SERIE A CLEAN

         Date HomeTeam    AwayTeam  FTHG  FTAG FTR  HS  AS  HST  AST
0  17/08/2024    Genoa       Inter     2     2   D  10  14    6    9
1  17/08/2024    Parma  Fiorentina     1     1   D  13  14    5    7
2  17/08/2024   Empoli       Monza     0     0   D   9   4    1    1
3  17/08/2024    Milan      Torino     2     2   D  20   6    6    3
4  18/08/2024  Bologna     Udinese     1     1   D  22   4    7    2

PREMIER CLEAN

         Date    HomeTeam     AwayTeam  FTHG  FTAG FTR  HS  AS  HST  AST
0  16/08/2024  Man United       Fulham     1     0   H  14  10    5    2
1  17/08/2024     Ipswich    Liverpool     0     2   A   7  18    2    5
2  17/08/2024     Arsenal       Wolves     2     0   H  18   9    6    3
3  17/08/2024     Everton     Brighton     0     3   A   9  10    1    5
4  17/08/2024   Newcastle  Southampton     1     0   H   3  19    1    4

LIGA CLEAN

         Date    HomeTeam AwayTeam  FTHG  FTAG FTR  HS  AS  HST  AST
0  15/08/2024  Ath Bilbao   Getafe     1     1   D   7   9    4    2
1  15/08/2024       Betis   Girona     1     1   D  19  13    4    2
2  16/08/2024       Celta   Alaves     2     1   H   6  10    4    2
3  16/08/2024  Las Palmas  Sevilla     2     2   D  13  16    5    5
4  17/08/2024     Osasuna  Leganes     1     1   D  16  10    5    4

In [6]:
# PERCORSO CARTELLA DATI PULITI

PATH_CLEAN = r"C:\Users\bello\Desktop\CAPSTONE\Capstone_calcio_2425\data_clean (dati_puliti)"

In [7]:
# SALVATAGGIO DEI 3 FILE CLEAN NELLA CARTELLA DATA_CLEAN

serie_a_clean.to_csv(PATH_CLEAN + r"\matches_serie_a_clean.csv", index=False)
premier_clean.to_csv(PATH_CLEAN + r"\matches_premier_league_clean.csv", index=False)
liga_clean.to_csv(PATH_CLEAN + r"\matches_liga_clean.csv", index=False)

print("FILE CLEAN SALVATI NELLA CARTELLA DATA_CLEAN")

FILE CLEAN SALVATI NELLA CARTELLA DATA_CLEAN